spring.application.name=backend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/novustrack
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate (ORM) Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}